[project]
name = "taipy-course-gui"
version = "0.1.0"
description = "Material for the Taipy onboarding course."
requires-python = ">=3.10, <3.13"
dependencies = [
    "taipy-enterprise==4.1.1",
    "plotly",
    "ipykernel",
    "nbformat",
]

[tool.ruff]
line-length = 120

[tool.uv.sources]
taipy-enterprise = { git = "ssh://git@github.com/Avaiga/taipy-enterprise.git", rev = "4.1.1" }
